name = "zarchify/zarch"
version = "0.1.4"
description = "A strictly typed heirarchical state machine library for roblox."
authors = ["zarch"]
repository = "https://github.com/zarchify/zarch"
license = "MIT"
includes = [
    "pesde.toml",
    "wally.toml",
    "README.md",
    "src/**/*.luau"
]

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]


[indices]
default = "https://github.com/pesde-pkg/index"
[wally_indices]
default = "https://github.com/UpliftGames/wally-index"


[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.2.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.5.1", target = "lune" }
testez = { wally = "roblox/testez", version = "^0.4.1", target = "roblox" }

[engines]
pesde = "^0.7.0"
lune = "^0.10.2"

[dependencies]
